const MENU_DATA = {

  // ==============================
  // PAKET NASI (GOFOOD)
  // ==============================
  'nasi-ayam-goreng': {
    id: 'nasi-ayam-goreng',
    nama: 'Nasi Ayam Goreng',
    harga: 24000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Ayam Goreng, Sayur Kapau, Sambal, Lalapan',
    tags: ['Ayam', 'Paket Nasi', 'Goreng'],
    pedas: 2,
    berat: '± 350 gram',
    kalori: '520 kkal',
    rating: 4.8,
    ulasan: 180,
    img: 'img/Screenshot 2026-08-06 085011.png',
    thumbnails: ['img/Screenshot 2026-08-06 085011.png']
  },
  'nasi-ayam-rendang': {
    id: 'nasi-ayam-rendang',
    nama: 'Nasi Ayam Rendang',
    harga: 24000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Ayam Rendang, Sayur Kapau, Sambal, Lalapan',
    tags: ['Ayam', 'Paket Nasi', 'Rendang'],
    pedas: 4,
    berat: '± 350 gram',
    kalori: '540 kkal',
    rating: 4.9,
    ulasan: 195,
    img: 'img/Screenshot 2026-08-06 084809.png',
    thumbnails: ['img/Screenshot 2026-08-06 084809.png']
  },
  'nasi-ayam-gulai': {
    id: 'nasi-ayam-gulai',
    nama: 'Nasi Ayam Gulai',
    harga: 24000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Ayam Gulai, Sayur Kapau, Sambal, Lalapan',
    tags: ['Ayam', 'Paket Nasi', 'Gulai'],
    pedas: 3,
    berat: '± 350 gram',
    kalori: '530 kkal',
    rating: 4.8,
    ulasan: 165,
    img: 'img/Screenshot 2026-08-06 084832.png',
    thumbnails: ['img/Screenshot 2026-08-06 084832.png']
  },
  'nasi-ayam-bakar': {
    id: 'nasi-ayam-bakar',
    nama: 'Nasi Ayam Bakar',
    harga: 24000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Ayam Bakar, Sayur Kapau, Sambal, Lalapan',
    tags: ['Ayam', 'Paket Nasi', 'Bakar'],
    pedas: 2,
    berat: '± 350 gram',
    kalori: '510 kkal',
    rating: 4.8,
    ulasan: 172,
    img: 'img/Screenshot 2026-08-06 085018.png',
    thumbnails: ['img/Screenshot 2026-08-06 085018.png']
  },
  'nasi-rendang': {
    id: 'nasi-rendang',
    nama: 'Nasi Rendang',
    harga: 27600,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Rendang Daging, Sayur Kapau, Sambal, Lalapan',
    tags: ['Daging Sapi', 'Paket Nasi', 'Rendang'],
    pedas: 4,
    berat: '± 380 gram',
    kalori: '590 kkal',
    rating: 4.9,
    ulasan: 230,
    img: 'img/Screenshot 2026-08-06 084738.png',
    thumbnails: ['img/Screenshot 2026-08-06 084738.png']
  },
  'nasi-kalio-hati': {
    id: 'nasi-kalio-hati',
    nama: 'Nasi Kalio Hati',
    harga: 24000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Kalio Hati, Sayur Kapau, Sambal, Lalapan',
    tags: ['Sapi', 'Paket Nasi', 'Kalio'],
    pedas: 3,
    berat: '± 340 gram',
    kalori: '500 kkal',
    rating: 4.7,
    ulasan: 140,
    img: 'img/Screenshot 2026-08-06 084824.png',
    thumbnails: ['img/Screenshot 2026-08-06 084824.png']
  },
  'nasi-kalio-limpa': {
    id: 'nasi-kalio-limpa',
    nama: 'Nasi Kalio Limpa',
    harga: 24000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Kalio Limpa, Sayur Kapau, Sambal, Lalapan',
    tags: ['Sapi', 'Paket Nasi', 'Kalio'],
    pedas: 3,
    berat: '± 340 gram',
    kalori: '490 kkal',
    rating: 4.7,
    ulasan: 135,
    img: 'img/Screenshot 2026-08-06 084756.png',
    thumbnails: ['img/Screenshot 2026-08-06 084756.png']
  },
  'nasi-telur-dadar': {
    id: 'nasi-telur-dadar',
    nama: 'Nasi Telur Dadar',
    harga: 18000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Telur Dadar, Sayur Kapau, Sambal, Lalapan',
    tags: ['Telur', 'Paket Nasi'],
    pedas: 2,
    berat: '± 300 gram',
    kalori: '420 kkal',
    rating: 4.8,
    ulasan: 160,
    img: 'img/Screenshot 2026-08-06 085715.png',
    thumbnails: ['img/Screenshot 2026-08-06 085715.png']
  },
  'nasi-perkedel-kentang': {
    id: 'nasi-perkedel-kentang',
    nama: 'Nasi Perkedel Kentang',
    harga: 15000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Perkedel Kentang, Sayur Kapau, Sambal, Lalapan',
    tags: ['Perkedel', 'Paket Nasi'],
    pedas: 1,
    berat: '± 280 gram',
    kalori: '380 kkal',
    rating: 4.7,
    ulasan: 145,
    img: 'img/Screenshot 2026-08-06 085710.png',
    thumbnails: ['img/Screenshot 2026-08-06 085710.png']
  },
  'nasi-sayur-komplit': {
    id: 'nasi-sayur-komplit',
    nama: 'Nasi Sayur Komplit',
    harga: 10000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Sayur Kapau, Sambal, Lalapan',
    tags: ['Sayur', 'Paket Nasi'],
    pedas: 2,
    berat: '± 250 gram',
    kalori: '320 kkal',
    rating: 4.8,
    ulasan: 175,
    img: 'img/Screenshot 2026-08-06 085602.png',
    thumbnails: ['img/Screenshot 2026-08-06 085602.png']
  },
  'nasi-telur-bulat': {
    id: 'nasi-telur-bulat',
    nama: 'Nasi Telur Bulat',
    harga: 16000,
    kategori: 'Paket Nasi',
    deskripsi: 'Nasi Putih, Telur Bulat, Sayur Kapau, Sambal, Lalapan',
    tags: ['Telur', 'Paket Nasi'],
    pedas: 2,
    berat: '± 290 gram',
    kalori: '400 kkal',
    rating: 4.6,
    ulasan: 120,
    img: 'img/Screenshot 2026-08-06 085704.png',
    thumbnails: ['img/Screenshot 2026-08-06 085704.png']
  },
  'ketupat-sayur-kapau': {
    id: 'ketupat-sayur-kapau',
    nama: 'Ketupat Sayur Kapau',
    harga: 18000,
    kategori: 'Paket Nasi Box',
    deskripsi: 'Ketupat dipadukan dengan sayur kapau dan kuah santan yang gurih nikmat memanjakan lidah dipagi hari kombinasi dengan rendang daging / telur gulai / kikil, menambah cita rasa ketupat sayur.',
    tags: ['Sarapan', 'Ketupat', 'Sayur Kapau'],
    pedas: 3,
    berat: '± 300 gram',
    kalori: '450 kkal',
    rating: 4.9,
    ulasan: 155,
    img: 'img/Screenshot 2026-08-06 085735.png',
    thumbnails: ['img/Screenshot 2026-08-06 085735.png']
  },



  // ==============================
  // LAUK SATUAN (SAPI, AYAM, BEBEK, IKAN, SEAFOOD)
  // ==============================

  'rendang-sapi-bukittinggi': {
    id: 'rendang-sapi-bukittinggi',
    nama: 'Rendang Sapi Bukit Tinggi',
    harga: 28000,
    kategori: 'Lauk',
    deskripsi: 'Daging sapi olahan khas Bukittinggi dimasak dengan bumbu rempah-rempah otentik hingga meresap sempurna dan berwarna pekat gurih nikmat.',
    tags: ['Daging Sapi', 'Bukittinggi', 'Otentik'],
    pedas: 4,
    berat: '± 150 gram',
    kalori: '330 kkal',
    rating: 4.9,
    ulasan: 195,
    img: 'img/Screenshot 2026-08-06 084738.png',
    thumbnails: ['img/Screenshot 2026-08-06 084738.png']
  },
  'limpa-sapi-kalio': {
    id: 'limpa-sapi-kalio',
    nama: 'Limpa Sapi Kalio',
    harga: 22000,
    kategori: 'Lauk',
    deskripsi: 'Limpa sapi empuk yang dimasak kuah kalio gurih berrempah khas Pesona Kapau.',
    tags: ['Limpa Sapi', 'Kalio'],
    pedas: 3,
    berat: '± 130 gram',
    kalori: '270 kkal',
    rating: 4.7,
    ulasan: 112,
    img: 'img/Screenshot 2026-08-06 084756.png',
    thumbnails: ['img/Screenshot 2026-08-06 084756.png']
  },
  'tunjang-sapi': {
    id: 'tunjang-sapi',
    nama: 'Tunjang Sapi (Kikil)',
    harga: 26000,
    kategori: 'Lauk',
    deskripsi: 'Kikil / tunjang sapi pilihan yang empuk dan kenyal, disajikan dalam kuah gulai santan kuning khas Padang. (Best Seller)',
    tags: ['Kikil', 'Santan', 'Best Seller'],
    pedas: 3,
    berat: '± 180 gram',
    kalori: '310 kkal',
    rating: 4.9,
    ulasan: 230,
    img: 'img/Screenshot 2026-08-06 084809.png',
    thumbnails: ['img/Screenshot 2026-08-06 084809.png']
  },
  'asam-padeh-gajebo': {
    id: 'asam-padeh-gajebo',
    nama: 'Asam Padeh Gajebo',
    harga: 27000,
    kategori: 'Lauk',
    deskripsi: 'Daging gajebo gurih dengan kuah asam padeh yang segar dan pedas mantap khas Minang. (Best Seller)',
    tags: ['Daging Sapi', 'Asam Padeh', 'Best Seller'],
    pedas: 4,
    berat: '± 150 gram',
    kalori: '340 kkal',
    rating: 4.9,
    ulasan: 205,
    img: 'img/Screenshot 2026-08-06 084824.png',
    thumbnails: ['img/Screenshot 2026-08-06 084824.png']
  },
  'hati-sapi-kalio': {
    id: 'hati-sapi-kalio',
    nama: 'Hati Sapi Kalio',
    harga: 22000,
    kategori: 'Lauk',
    deskripsi: 'Hati sapi olahan bertekstur lembut disiram kuah kalio kental nan gurih kaya rempah.',
    tags: ['Hati Sapi', 'Kalio'],
    pedas: 3,
    berat: '± 140 gram',
    kalori: '280 kkal',
    rating: 4.7,
    ulasan: 104,
    img: 'img/Screenshot 2026-08-06 084832.png',
    thumbnails: ['img/Screenshot 2026-08-06 084832.png']
  },
  'dendeng-kering': {
    id: 'dendeng-kering',
    nama: 'Dendeng Kering',
    harga: 28000,
    kategori: 'Lauk',
    deskripsi: 'Irisan daging sapi tipis yang digoreng hingga garing dan renyah beraroma gurih rempah khas Padang.',
    tags: ['Daging Sapi', 'Goreng', 'Renyah'],
    pedas: 2,
    berat: '± 100 gram',
    kalori: '290 kkal',
    rating: 4.8,
    ulasan: 168,
    img: 'img/Screenshot 2026-08-06 084929.png',
    thumbnails: ['img/Screenshot 2026-08-06 084929.png']
  },
  'paru-kering': {
    id: 'paru-kering',
    nama: 'Paru Kering',
    harga: 24000,
    kategori: 'Lauk',
    deskripsi: 'Paru sapi goreng renyah dan gurih, pas menjadi lauk pendamping santapan nasi Padang.',
    tags: ['Paru Sapi', 'Goreng', 'Renyah'],
    pedas: 2,
    berat: '± 110 gram',
    kalori: '270 kkal',
    rating: 4.8,
    ulasan: 175,
    img: 'img/Screenshot 2026-08-06 084917.png',
    thumbnails: ['img/Screenshot 2026-08-06 084917.png']
  },
  'dendeng-cabai-merah': {
    id: 'dendeng-cabai-merah',
    nama: 'Dendeng Cabai Merah',
    harga: 28000,
    kategori: 'Lauk',
    deskripsi: 'Dendeng sapi goreng disajikan dengan baluran sambal cabai merah pecah yang pedas nikmat.',
    tags: ['Daging Sapi', 'Pedas', 'Sambal Merah'],
    pedas: 5,
    berat: '± 120 gram',
    kalori: '300 kkal',
    rating: 4.9,
    ulasan: 188,
    img: 'img/Screenshot 2026-08-06 084936.png',
    thumbnails: ['img/Screenshot 2026-08-06 084936.png']
  },
  'tambusu': {
    id: 'tambusu',
    nama: 'Tambusu (Usus Sapi Isi Telur)',
    harga: 27000,
    kategori: 'Lauk',
    deskripsi: 'Kami menyediakan menu olahan khas dari BUKIT TINGGI. TAMBUSU usus sapi yang di isi dengan telur. Salah satu makanan otentik dari bukit tinggi yang sudah terkenal, dipadukan dengan kuah gulai nikmat.',
    tags: ['Spesial', 'Gulai', 'Bukittinggi', 'Best Seller'],
    pedas: 3,
    berat: '± 180 gram',
    kalori: '350 kkal',
    rating: 5.0,
    ulasan: 280,
    img: 'img/Screenshot 2026-08-06 085202.png',
    thumbnails: ['img/Screenshot 2026-08-06 085202.png']
  },
  'gulai-banak': {
    id: 'gulai-banak',
    nama: 'Gulai Banak (Otak Sapi)',
    harga: 26000,
    kategori: 'Lauk',
    deskripsi: 'Gulai banak adalah gulai otak sapi yang di masak dengan kuah gulai asam pedas yang segar dan nikmat sebagai lauk pendamping nasi padang.',
    tags: ['Otak Sapi', 'Gulai', 'Asam Pedas', 'Best Seller'],
    pedas: 3,
    berat: '± 160 gram',
    kalori: '290 kkal',
    rating: 4.9,
    ulasan: 190,
    img: 'img/Screenshot 2026-08-06 085215.png',
    thumbnails: ['img/Screenshot 2026-08-06 085215.png']
  },
  'cincang-kambing': {
    id: 'cincang-kambing',
    nama: 'Cincang Kambing',
    harga: 30000,
    kategori: 'Lauk',
    deskripsi: 'menu olahan cincang kambing kami adalah menu otentik dari bukit tinggi, daging kambing yang di masak dengan bumbu kaya rempah serta kuah santan yang kental menjadikan rasa daging kambing semakin nikmat.',
    tags: ['Kambing', 'Cincang', 'Santan', 'Best Seller'],
    pedas: 4,
    berat: '± 200 gram',
    kalori: '380 kkal',
    rating: 4.9,
    ulasan: 220,
    img: 'img/Screenshot 2026-08-06 085227.png',
    thumbnails: ['img/Screenshot 2026-08-06 085227.png']
  },
  'sop-buntut-iga': {
    id: 'sop-buntut-iga',
    nama: 'Sop Buntut dan Iga Sapi',
    harga: 35000,
    kategori: 'Lauk',
    deskripsi: 'Sop Buntut dan Iga sapi yang masak dengan bumbu kaya rempah dan teksture buntuk dan iga yang lembut disajikan dalam kondisi panas menjadikan menu makan anda semakin nikmat.',
    tags: ['Sop Sapi', 'Iga', 'Buntut', 'Best Seller'],
    pedas: 1,
    berat: '± 350 gram',
    kalori: '420 kkal',
    rating: 5.0,
    ulasan: 245,
    img: 'img/Screenshot 2026-08-06 085726.png',
    thumbnails: ['img/Screenshot 2026-08-06 085726.png']
  },
  'ayam-kemangi': {
    id: 'ayam-kemangi',
    nama: 'Ayam Kemangi',
    harga: 20000,
    kategori: 'Lauk',
    deskripsi: 'Olahan ayam bumbu rempah kuning yang dipadukan dengan aroma daun kemangi segar yang harum dan gurih.',
    tags: ['Ayam', 'Kemangi', 'Harum'],
    pedas: 3,
    berat: '± 150 gram',
    kalori: '270 kkal',
    rating: 4.8,
    ulasan: 135,
    img: 'img/Screenshot 2026-08-06 084950.png',
    thumbnails: ['img/Screenshot 2026-08-06 084950.png']
  },
  'ayam-goreng-bumbu': {
    id: 'ayam-goreng-bumbu',
    nama: 'Ayam Goreng Bumbu',
    harga: 18000,
    kategori: 'Lauk',
    deskripsi: 'Ayam goreng dengan taburan bumbu rempah goreng khas Padang yang gurih dan renyah.',
    tags: ['Ayam', 'Goreng', 'Bumbu'],
    pedas: 1,
    berat: '± 140 gram',
    kalori: '260 kkal',
    rating: 4.7,
    ulasan: 140,
    img: 'img/Screenshot 2026-08-06 085011.png',
    thumbnails: ['img/Screenshot 2026-08-06 085011.png']
  },
  'ayam-rendang': {
    id: 'ayam-rendang',
    nama: 'Ayam Masak Rendang',
    harga: 20000,
    kategori: 'Lauk',
    deskripsi: 'Ayam paha dimasak dengan bumbu rendang khas Padang yang kaya rempah, pedas dan gurih.',
    tags: ['Ayam', 'Pedas', 'Rendang'],
    pedas: 4,
    berat: '± 150 gram',
    kalori: '290 kkal',
    rating: 4.8,
    ulasan: 178,
    img: 'img/Screenshot 2026-08-06 084959.png',
    thumbnails: ['img/Screenshot 2026-08-06 084959.png']
  },
  'ayam-bakar': {
    id: 'ayam-bakar',
    nama: 'Ayam Bakar Padang',
    harga: 20000,
    kategori: 'Lauk',
    deskripsi: 'Ayam pilihan yang dibakar dengan bumbu rempah padang hingga harum meresap ke dalam daging.',
    tags: ['Ayam', 'Bakar'],
    pedas: 3,
    berat: '± 150 gram',
    kalori: '280 kkal',
    rating: 4.8,
    ulasan: 160,
    img: 'img/Screenshot 2026-08-06 085018.png',
    thumbnails: ['img/Screenshot 2026-08-06 085018.png']
  },
  'ayam-gulai': {
    id: 'gulai-ayam',
    nama: 'Gulai Ayam',
    harga: 22000,
    kategori: 'Lauk',
    deskripsi: 'Ayam dimasak gulai santan kuning khas Minang, kaya rempah-rempah khas Padang dan sangat gurih.',
    tags: ['Ayam', 'Gulai', 'Santan'],
    pedas: 3,
    berat: '± 150 gram',
    kalori: '280 kkal',
    rating: 4.7,
    ulasan: 95,
    img: 'img/Screenshot 2026-08-06 085024.png',
    thumbnails: ['img/Screenshot 2026-08-06 085024.png']
  },
  'ayam-cabai-merah': {
    id: 'ayam-cabai-merah',
    nama: 'Ayam Cabai Merah',
    harga: 20000,
    kategori: 'Lauk',
    deskripsi: 'Ayam potong goreng disajikan dengan baluran sambal cabai merah khas Minang yang pedas gurih.',
    tags: ['Ayam', 'Pedas', 'Sambal Merah'],
    pedas: 4,
    berat: '± 150 gram',
    kalori: '280 kkal',
    rating: 4.7,
    ulasan: 125,
    img: 'img/Screenshot 2026-08-06 085033.png',
    thumbnails: ['img/Screenshot 2026-08-06 085033.png']
  },
  'itik-lado-mudo': {
    id: 'itik-lado-mudo',
    nama: 'Itik Lado Mudo',
    harga: 32000,
    kategori: 'Lauk',
    deskripsi: 'Kami menyediakan menu olahan bebek khas dari minang kabau. bebek yang di masak dengan cabai hijau. Dengan rasa yang istimewa yang akan memuaskan selera.',
    tags: ['Bebek', 'Cabai Hijau', 'Minang'],
    pedas: 4,
    berat: '± 200 gram',
    kalori: '360 kkal',
    rating: 4.9,
    ulasan: 170,
    img: 'img/Screenshot 2026-08-06 085441.png',
    thumbnails: ['img/Screenshot 2026-08-06 085441.png']
  },
  'ayam-pop': {
    id: 'ayam-pop',
    nama: 'Ayam Pop',
    harga: 20000,
    kategori: 'Lauk',
    deskripsi: 'Kami menyediakan menu olahan ayam pop putih yang di masak dengan rempah dan air kelapa yang manis. Menjadikan ayam pop menu yang mempunyai rasa yang menggugah selera, di padukan dengan sambal merah ayam pop menjadikan menu santap anda semakin nikmat.',
    tags: ['Ayam Pop', 'Sambal Merah', 'Best Seller'],
    pedas: 1,
    berat: '± 140 gram',
    kalori: '240 kkal',
    rating: 4.9,
    ulasan: 215,
    img: 'img/Screenshot 2026-08-06 085454.png',
    thumbnails: ['img/Screenshot 2026-08-06 085454.png']
  },


  // IKAN & SEAFOOD
  'kepala-ikan-kakap': {
    id: 'kepala-ikan-kakap',
    nama: 'Kepala Ikan Kakap',
    harga: 75000,
    kategori: 'Lauk',
    deskripsi: 'spesial Ikan Kepala Kakap merah yang di masak kuah kuning asam khas pesona kapau, kuah yang segar di padukan dengan kepala ikan kakap yang gurih menjadi pembangkit selera makan anda.',
    tags: ['Kepala Kakap', 'Spesial', 'Pesona Kapau'],
    pedas: 3,
    berat: '± 500 gram',
    kalori: '450 kkal',
    rating: 5.0,
    ulasan: 310,
    img: 'img/Screenshot 2026-08-06 085045.png',
    thumbnails: ['img/Screenshot 2026-08-06 085045.png']
  },
  'gulai-kakap-fillet': {
    id: 'gulai-kakap-fillet',
    nama: 'Gulai Kakap Fillet',
    harga: 25000,
    kategori: 'Lauk',
    deskripsi: 'Daging fillet ikan kakap tanpa duri yang lembut dimasak dalam kuah gulai santan kuning gurih khas Minang.',
    tags: ['Kakap', 'Fillet', 'Gulai'],
    pedas: 2,
    berat: '± 150 gram',
    kalori: '250 kkal',
    rating: 4.8,
    ulasan: 120,
    img: 'img/Screenshot 2026-08-06 085508.png',
    thumbnails: ['img/Screenshot 2026-08-06 085508.png']
  },
  'ikan-nila-bakar': {
    id: 'ikan-nila-bakar',
    nama: 'Ikan Nila Bakar',
    harga: 22000,
    kategori: 'Lauk',
    deskripsi: 'Ikan nila segar dibakar dengan baluran bumbu bumbu kuning padang yang manis gurih beraroma asap harum.',
    tags: ['Ikan Nila', 'Bakar'],
    pedas: 2,
    berat: '± 200 gram',
    kalori: '280 kkal',
    rating: 4.7,
    ulasan: 110,
    img: 'img/Screenshot 2026-08-06 085100.png',
    thumbnails: ['img/Screenshot 2026-08-06 085100.png']
  },
  'ikan-gembung-goreng': {
    id: 'ikan-gembung-goreng',
    nama: 'Ikan Gembung Goreng',
    harga: 18000,
    kategori: 'Lauk',
    deskripsi: 'Ikan gembung goreng garing renyah disajikan dengan taburan bumbu rempah gurih khas Padang.',
    tags: ['Ikan Gembung', 'Goreng'],
    pedas: 1,
    berat: '± 160 gram',
    kalori: '230 kkal',
    rating: 4.6,
    ulasan: 95,
    img: 'img/Screenshot 2026-08-06 085109.png',
    thumbnails: ['img/Screenshot 2026-08-06 085109.png']
  },
  'ikan-gembung-sambal-mentah': {
    id: 'ikan-gembung-sambal-mentah',
    nama: 'Ikan Gembung Sambal Mentah',
    harga: 19000,
    kategori: 'Lauk',
    deskripsi: 'Ikan gembung goreng disajikan dengan irisan sambal mentah dabu-dabu khas yang pedas dan segar.',
    tags: ['Ikan Gembung', 'Sambal Mentah'],
    pedas: 4,
    berat: '± 160 gram',
    kalori: '240 kkal',
    rating: 4.7,
    ulasan: 105,
    img: 'img/Screenshot 2026-08-06 085117.png',
    thumbnails: ['img/Screenshot 2026-08-06 085117.png']
  },
  'ikan-gembung-pepes': {
    id: 'ikan-gembung-pepes',
    nama: 'Ikan Gembung Pepes',
    harga: 20000,
    kategori: 'Lauk',
    deskripsi: 'Pepes ikan gembung bumbu rempah berbalut daun pisang yang dibakar aroma harum khas meresap sempurna.',
    tags: ['Ikan Gembung', 'Pepes'],
    pedas: 3,
    berat: '± 170 gram',
    kalori: '220 kkal',
    rating: 4.8,
    ulasan: 115,
    img: 'img/Screenshot 2026-08-06 085127.png',
    thumbnails: ['img/Screenshot 2026-08-06 085127.png']
  },
  'ikan-bilih-goreng': {
    id: 'ikan-bilih-goreng',
    nama: 'Ikan Bilih Goreng',
    harga: 20000,
    kategori: 'Lauk',
    deskripsi: 'Ikan bilih khas Danau Singkarak Minang yang digoreng garing dan renyah gurih disajikan dengan sambal.',
    tags: ['Ikan Bilih', 'Danau Singkarak', 'Khas Minang'],
    pedas: 3,
    berat: '± 100 gram',
    kalori: '210 kkal',
    rating: 4.9,
    ulasan: 160,
    img: 'img/Screenshot 2026-08-06 085139.png',
    thumbnails: ['img/Screenshot 2026-08-06 085139.png']
  },
  'ikan-lele-goreng': {
    id: 'ikan-lele-goreng',
    nama: 'Ikan Lele Goreng',
    harga: 15000,
    kategori: 'Lauk',
    deskripsi: 'Ikan lele goreng renyah bumbu rempah disajikan dengan kremesan dan sambal padang nikmat.',
    tags: ['Ikan Lele', 'Goreng'],
    pedas: 2,
    berat: '± 150 gram',
    kalori: '220 kkal',
    rating: 4.6,
    ulasan: 88,
    img: 'img/Screenshot 2026-08-06 085146.png',
    thumbnails: ['img/Screenshot 2026-08-06 085146.png']
  },
  'cumi-sambal-merah': {
    id: 'cumi-sambal-merah',
    nama: 'Cumi Cumi Sambal Merah',
    harga: 25000,
    kategori: 'Lauk',
    deskripsi: 'Olahan cumi-cumi segar empuk dipadukan dengan kuah sambal merah pedas manis mantap.',
    tags: ['Cumi', 'Sambal Merah', 'Seafood'],
    pedas: 4,
    berat: '± 150 gram',
    kalori: '260 kkal',
    rating: 4.8,
    ulasan: 145,
    img: 'img/Screenshot 2026-08-06 085516.png',
    thumbnails: ['img/Screenshot 2026-08-06 085516.png']
  },
  'udang-sambal-merah': {
    id: 'udang-sambal-merah',
    nama: 'Udang Sambal Merah',
    harga: 25000,
    kategori: 'Lauk',
    deskripsi: 'Udang segar dimasak bumbu sambal merah khas padang dengan rasa gurih pedas manis yang menggoda.',
    tags: ['Udang', 'Sambal Merah', 'Seafood'],
    pedas: 4,
    berat: '± 140 gram',
    kalori: '250 kkal',
    rating: 4.8,
    ulasan: 150,
    img: 'img/Screenshot 2026-08-06 085523.png',
    thumbnails: ['img/Screenshot 2026-08-06 085523.png']
  },
  'perkedel': {
    id: 'perkedel',
    nama: 'Perkedel',
    harga: 5000,
    kategori: 'Lauk',
    deskripsi: 'Perkedel kentang lembut dan gurih renyah khas Minang, pelengkap sempurna makanan Padang.',
    tags: ['Perkedel', 'Kentang', 'Gurih'],
    pedas: 0,
    berat: '± 80 gram',
    kalori: '140 kkal',
    rating: 4.8,
    ulasan: 110,
    img: 'img/Screenshot 2026-08-06 085710.png',
    thumbnails: ['img/Screenshot 2026-08-06 085710.png']
  },
  'telur-balado': {
    id: 'telur-balado',
    nama: 'Telur Balado',
    harga: 7000,
    kategori: 'Lauk',
    deskripsi: 'Telur ayam bulat goreng dengan baluran sambal balado merah pedas manis gurih.',
    tags: ['Telur', 'Balado'],
    pedas: 3,
    berat: '± 90 gram',
    kalori: '180 kkal',
    rating: 4.7,
    ulasan: 95,
    img: 'img/Screenshot 2026-08-06 085704.png',
    thumbnails: ['img/Screenshot 2026-08-06 085704.png']
  },
  'telur-dadar': {
    id: 'telur-dadar',
    nama: 'Telur Dadar Padang',
    harga: 8000,
    kategori: 'Lauk',
    deskripsi: 'Telur dadar tebal khas Padang dengan campuran daun bawang dan rempah yang gurih renyah di luar lembut di dalam.',
    tags: ['Telur', 'Dadar Padang'],
    pedas: 1,
    berat: '± 110 gram',
    kalori: '210 kkal',
    rating: 4.8,
    ulasan: 140,
    img: 'img/Screenshot 2026-08-06 085715.png',
    thumbnails: ['img/Screenshot 2026-08-06 085715.png']
  },

  // ==============================
  // SAYUR & JENGKOL
  // ==============================
  'sayur-kapau': {
    id: 'sayur-kapau',
    nama: 'Sayur Kapau',
    harga: 5000,
    kategori: 'Sayur',
    deskripsi: 'Sayur kapau berbeda dengan sayur masakan padang lainnya. Cita rasa otentik khas kapau yang akan menambah pengalaman memakan nasi padang yang berbeda untuk anda.',
    tags: ['Sayur', 'Santan', 'Kapau'],
    pedas: 2,
    berat: '± 200 gram',
    kalori: '160 kkal',
    rating: 4.8,
    ulasan: 145,
    img: 'img/Screenshot 2026-08-06 085602.png',
    thumbnails: ['img/Screenshot 2026-08-06 085602.png']
  },
  'gulai-singkong': {
    id: 'gulai-singkong',
    nama: 'Gulai Daun Singkong',
    harga: 5000,
    kategori: 'Sayur',
    deskripsi: 'Daun singkong dimasak gulai santan khas Padang dengan cita rasa gurih dan bumbu rempah pilihan.',
    tags: ['Sayur', 'Santan'],
    pedas: 2,
    berat: '± 180 gram',
    kalori: '180 kkal',
    rating: 4.6,
    ulasan: 80,
    img: 'img/d3f1a9ad74bb9ce6050ae1f6ee87763a.jpg',
    thumbnails: ['img/d3f1a9ad74bb9ce6050ae1f6ee87763a.jpg']
  },
  'daun-ubi': {
    id: 'daun-ubi',
    nama: 'Daun Ubi / Singkong Rebus',
    harga: 4000,
    kategori: 'Sayur',
    deskripsi: 'Rebusan daun singkong/ubi segar pilihan, lembut dan hijau alami sebagai pendamping lauk nasi Padang.',
    tags: ['Sayur', 'Daun Singkong'],
    pedas: 0,
    berat: '± 150 gram',
    kalori: '90 kkal',
    rating: 4.6,
    ulasan: 65,
    img: 'img/Screenshot 2026-08-06 085536.png',
    thumbnails: ['img/Screenshot 2026-08-06 085536.png']
  },
  'rendang-jengkol': {
    id: 'rendang-jengkol',
    nama: 'Rendang Jengkol',
    harga: 12000,
    kategori: 'Sayur',
    deskripsi: 'Jengkol empuk olahan khas dimasak bumbu rendang padang yang legit, gurih, dan pedas mantap.',
    tags: ['Jengkol', 'Rendang', 'Pedas'],
    pedas: 4,
    berat: '± 150 gram',
    kalori: '240 kkal',
    rating: 4.8,
    ulasan: 130,
    img: 'img/Screenshot 2026-08-06 085626.png',
    thumbnails: ['img/Screenshot 2026-08-06 085626.png']
  },
  'sayur-tauge': {
    id: 'sayur-tauge',
    nama: 'Sayur Tauge Tahu',
    harga: 5000,
    kategori: 'Sayur',
    deskripsi: 'Tumis sayur tauge segar dengan tahu yang renyah dan gurih, pelengkap sempurna makanan padang.',
    tags: ['Sayur', 'Tauge'],
    pedas: 1,
    berat: '± 150 gram',
    kalori: '110 kkal',
    rating: 4.5,
    ulasan: 58,
    img: 'img/Screenshot 2026-08-06 085632.png',
    thumbnails: ['img/Screenshot 2026-08-06 085632.png']
  },
  'jengkol-cabai-hijau': {
    id: 'jengkol-cabai-hijau',
    nama: 'Jengkol Cabai Hijau',
    harga: 12000,
    kategori: 'Sayur',
    deskripsi: 'Olahan jengkol empuk ditumis dengan sambal cabai hijau mentah khas Minang yang pedas dan harum.',
    tags: ['Jengkol', 'Cabai Hijau', 'Pedas'],
    pedas: 4,
    berat: '± 150 gram',
    kalori: '230 kkal',
    rating: 4.8,
    ulasan: 122,
    img: 'img/Screenshot 2026-08-06 085639.png',
    thumbnails: ['img/Screenshot 2026-08-06 085639.png']
  },
  'sambal-merah': {
    id: 'sambal-merah',
    nama: 'Sambal Merah',
    harga: 3000,
    kategori: 'Sayur',
    deskripsi: 'Sambal merah khas Padang dari cabai merah pilihan yang ditumis minyak gurih beraroma khas.',
    tags: ['Sambal', 'Pedas'],
    pedas: 4,
    berat: '± 50 gram',
    kalori: '80 kkal',
    rating: 4.7,
    ulasan: 85,
    img: 'img/Screenshot 2026-08-06 085547.png',
    thumbnails: ['img/Screenshot 2026-08-06 085547.png']
  },
  'sambal-hijau': {
    id: 'sambal-hijau',
    nama: 'Sambal Hijau',
    harga: 3000,
    kategori: 'Sayur',
    deskripsi: 'Sambal cabai hijau padang otentik dengan racikan tomat hijau dan rempah yang pedas gurih.',
    tags: ['Sambal', 'Cabai Hijau'],
    pedas: 3,
    berat: '± 50 gram',
    kalori: '70 kkal',
    rating: 4.8,
    ulasan: 98,
    img: 'img/Screenshot 2026-08-06 085611.png',
    thumbnails: ['img/Screenshot 2026-08-06 085611.png']
  },

  // ==============================
  // TAMBAHAN
  // ==============================
  'nasi-putih': {
    id: 'nasi-putih',
    nama: 'Nasi Putih',
    harga: 5000,
    kategori: 'Tambahan',
    deskripsi: 'Nasi putih hangat pulen khas beras pilihan pelengkap utama masakan Padang.',
    tags: ['Nasi', 'Pokok'],
    pedas: 0,
    berat: '± 200 gram',
    kalori: '240 kkal',
    rating: 4.8,
    ulasan: 210,
    img: 'img/Screenshot 2026-08-06 085648.png',
    thumbnails: ['img/Screenshot 2026-08-06 085648.png']
  },
  'kerupuk-jangek': {
    id: 'kerupuk-jangek',
    nama: 'Kerupuk Jangek',
    harga: 6000,
    kategori: 'Tambahan',
    deskripsi: 'Kerupuk kulit sapi (jangek) renyah khas Minang, makin nikmat disiram kuah gulai/kalio.',
    tags: ['Kerupuk', 'Kulit Sapi'],
    pedas: 0,
    berat: '± 30 gram',
    kalori: '120 kkal',
    rating: 4.9,
    ulasan: 175,
    img: 'img/Screenshot 2026-08-06 085657.png',
    thumbnails: ['img/Screenshot 2026-08-06 085657.png']
  },

  // ==============================
  // MINUMAN (KHAS MINANG, SODA, JUS, DLL)
  // ==============================
  'teh-telur': {
    id: 'teh-telur',
    nama: 'Teh Telur',
    harga: 12000,
    kategori: 'Minuman',
    deskripsi: 'Teh telur dan Kopi telur adalah minuman khas dari minang kabau yang dapat menjadi minuman yang meningkatkan stamina anda.',
    tags: ['Minuman Khas', 'Stamina', 'Khas Minang'],
    pedas: 0,
    berat: '± 250 ml',
    kalori: '180 kkal',
    rating: 4.9,
    ulasan: 165,
    img: 'img/Screenshot 2026-08-06 085757.png',
    thumbnails: ['img/Screenshot 2026-08-06 085757.png']
  },
  'kopi-telur': {
    id: 'kopi-telur',
    nama: 'Kopi Telur',
    harga: 14000,
    kategori: 'Minuman',
    deskripsi: 'Kopi dipadukan dengan kocokan telur khas Minangkabau yang kaya rasa dan dapat meningkatkan stamina anda.',
    tags: ['Minuman Khas', 'Kopi', 'Stamina'],
    pedas: 0,
    berat: '± 250 ml',
    kalori: '200 kkal',
    rating: 4.9,
    ulasan: 140,
    img: 'img/Screenshot 2026-08-06 085805.png',
    thumbnails: ['img/Screenshot 2026-08-06 085805.png']
  },
  'soda-strawberry': {
    id: 'soda-strawberry',
    nama: 'Soda Strawberry',
    harga: 12000,
    kategori: 'Minuman',
    deskripsi: 'Minuman es soda segar yang menyegarkan badan anda untuk semangat beraktivitas.',
    tags: ['Soda', 'Segar'],
    pedas: 0,
    berat: '± 300 ml',
    kalori: '130 kkal',
    rating: 4.7,
    ulasan: 88,
    img: 'img/Screenshot 2026-08-06 085815.png',
    thumbnails: ['img/Screenshot 2026-08-06 085815.png']
  },
  'soda-gembira': {
    id: 'soda-gembira',
    nama: 'Soda Gembira',
    harga: 14000,
    kategori: 'Minuman',
    deskripsi: 'Minuman es soda segar dipadukan susu kental manis dan sirup yang menyegarkan badan anda untuk semangat beraktivitas.',
    tags: ['Soda', 'Susu', 'Segar'],
    pedas: 0,
    berat: '± 350 ml',
    kalori: '160 kkal',
    rating: 4.8,
    ulasan: 102,
    img: 'img/Screenshot 2026-08-06 085823.png',
    thumbnails: ['img/Screenshot 2026-08-06 085823.png']
  },
  'jus-alpukat': {
    id: 'jus-alpukat',
    nama: 'Jus Alpukat',
    harga: 15000,
    kategori: 'Minuman',
    deskripsi: 'Jus buah alpukat segar alami pilihan disajikan dengan cocolan susu cokelat nikmat.',
    tags: ['Jus', 'Buah Segar'],
    pedas: 0,
    berat: '± 350 ml',
    kalori: '190 kkal',
    rating: 4.9,
    ulasan: 125,
    img: 'img/IMG_6964.PNG',
    thumbnails: ['img/IMG_6964.PNG']
  },
  'jus-mangga': {
    id: 'jus-mangga',
    nama: 'Jus Mangga',
    harga: 15000,
    kategori: 'Minuman',
    deskripsi: 'Jus buah mangga manis dan segar alami kaya vitamin C.',
    tags: ['Jus', 'Buah Segar'],
    pedas: 0,
    berat: '± 350 ml',
    kalori: '140 kkal',
    rating: 4.8,
    ulasan: 110,
    img: 'img/IMG_6964.PNG',
    thumbnails: ['img/IMG_6964.PNG']
  },
  'jus-sirsak': {
    id: 'jus-sirsak',
    nama: 'Jus Sirsak',
    harga: 15000,
    kategori: 'Minuman',
    deskripsi: 'Jus buah sirsak dengan cita rasa asam manis yang sangat menyegarkan.',
    tags: ['Jus', 'Buah Segar'],
    pedas: 0,
    berat: '± 350 ml',
    kalori: '130 kkal',
    rating: 4.7,
    ulasan: 85,
    img: 'img/IMG_6964.PNG',
    thumbnails: ['img/IMG_6964.PNG']
  },
  'jus-semangka': {
    id: 'jus-semangka',
    nama: 'Jus Semangka',
    harga: 15000,
    kategori: 'Minuman',
    deskripsi: 'Jus buah semangka segar yang mendinginkan dahaga.',
    tags: ['Jus', 'Buah Segar'],
    pedas: 0,
    berat: '± 350 ml',
    kalori: '110 kkal',
    rating: 4.8,
    ulasan: 90,
    img: 'img/IMG_6964.PNG',
    thumbnails: ['img/IMG_6964.PNG']
  },
  'jus-stroberi': {
    id: 'jus-stroberi',
    nama: 'Jus Stroberi',
    harga: 15000,
    kategori: 'Minuman',
    deskripsi: 'Jus buah stroberi manis asam segar kaya antioksidan.',
    tags: ['Jus', 'Buah Segar'],
    pedas: 0,
    berat: '± 350 ml',
    kalori: '120 kkal',
    rating: 4.7,
    ulasan: 80,
    img: 'img/IMG_6964.PNG',
    thumbnails: ['img/IMG_6964.PNG']
  },
  'jus-melon': {
    id: 'jus-melon',
    nama: 'Jus Melon',
    harga: 15000,
    kategori: 'Minuman',
    deskripsi: 'Jus buah melon manis harum dan menyegarkan.',
    tags: ['Jus', 'Buah Segar'],
    pedas: 0,
    berat: '± 350 ml',
    kalori: '120 kkal',
    rating: 4.7,
    ulasan: 75,
    img: 'img/IMG_6964.PNG',
    thumbnails: ['img/IMG_6964.PNG']
  },
  'teh-tarik': {
    id: 'teh-tarik',
    nama: 'Teh Tarik',
    harga: 15000,
    kategori: 'Minuman',
    deskripsi: 'Teh tarik nikmat berbusa lembut paduan teh dan susu yang gurih manis pas.',
    tags: ['Teh Tarik', 'Susu'],
    pedas: 0,
    berat: '± 300 ml',
    kalori: '140 kkal',
    rating: 4.8,
    ulasan: 115,
    img: 'img/Screenshot 2026-08-06 085839.png',
    thumbnails: ['img/Screenshot 2026-08-06 085839.png']
  },
  'teh-manis': {
    id: 'teh-manis',
    nama: 'Teh Manis',
    harga: 7000,
    kategori: 'Minuman',
    deskripsi: 'Teh manis segar disajikan dingin atau hangat pelengkap makan hidangan Minang.',
    tags: ['Teh', 'Manis'],
    pedas: 0,
    berat: '± 300 ml',
    kalori: '70 kkal',
    rating: 4.7,
    ulasan: 130,
    img: 'img/Screenshot 2026-08-06 085845.png',
    thumbnails: ['img/Screenshot 2026-08-06 085845.png']
  },
  'jeruk-peras': {
    id: 'jeruk-peras',
    nama: 'Jeruk Peras',
    harga: 15000,
    kategori: 'Minuman',
    deskripsi: 'Perasan jeruk manis segar pilihan disajikan dingin dengan es yang kaya vitamin C.',
    tags: ['Jeruk', 'Peras', 'Segar'],
    pedas: 0,
    berat: '± 300 ml',
    kalori: '110 kkal',
    rating: 4.8,
    ulasan: 105,
    img: 'img/Screenshot 2026-08-06 085850.png',
    thumbnails: ['img/Screenshot 2026-08-06 085850.png']
  },
  'lemon-tea': {
    id: 'lemon-tea',
    nama: 'Lemon Tea',
    harga: 15000,
    kategori: 'Minuman',
    deskripsi: 'Minuman teh diseduh segar dipadukan perasan jeruk lemon asli yang asam manis dingin.',
    tags: ['Lemon Tea', 'Segar'],
    pedas: 0,
    berat: '± 300 ml',
    kalori: '90 kkal',
    rating: 4.8,
    ulasan: 98,
    img: 'img/Screenshot 2026-08-06 085857.png',
    thumbnails: ['img/Screenshot 2026-08-06 085857.png']
  },
  'kopi-hitam': {
    id: 'kopi-hitam',
    nama: 'Kopi Hitam',
    harga: 8000,
    kategori: 'Minuman',
    deskripsi: 'Kopi hitam tradisional diseduh dengan cita rasa dan aroma kopi mantap.',
    tags: ['Kopi', 'Hitam'],
    pedas: 0,
    berat: '± 250 ml',
    kalori: '10 kkal',
    rating: 4.7,
    ulasan: 85,
    img: 'img/Screenshot 2026-08-06 085903.png',
    thumbnails: ['img/Screenshot 2026-08-06 085903.png']
  },
  'kopi-susu': {
    id: 'kopi-susu',
    nama: 'Kopi Susu',
    harga: 10000,
    kategori: 'Minuman',
    deskripsi: 'Paduan kopi hitam mantap dengan susu manis gurih yang memberikan kesegaran.',
    tags: ['Kopi', 'Susu'],
    pedas: 0,
    berat: '± 250 ml',
    kalori: '110 kkal',
    rating: 4.8,
    ulasan: 110,
    img: 'img/Screenshot 2026-08-06 085914.png',
    thumbnails: ['img/Screenshot 2026-08-06 085914.png']
  },
  'es-jeruk': {
    id: 'es-jeruk',
    nama: 'Es Jeruk',
    harga: 8000,
    kategori: 'Minuman',
    deskripsi: 'Minuman perasan jeruk manis asli yang segar dan dingin, pas sebagai penutup hidangan pedas.',
    tags: ['Minuman', 'Dingin', 'Segar'],
    pedas: 0,
    berat: '± 300 ml',
    kalori: '90 kkal',
    rating: 4.8,
    ulasan: 110,
    img: 'img/es jeruk.png',
    thumbnails: ['img/es jeruk.png']
  },
  'es-teh': {
    id: 'es-teh',
    nama: 'Es Teh Manis',
    harga: 5000,
    kategori: 'Minuman',
    deskripsi: 'Teh manis segar dengan es batu, minuman wajib pelengkap makan khas warung Padang.',
    tags: ['Minuman', 'Dingin', 'Teh'],
    pedas: 0,
    berat: '± 300 ml',
    kalori: '60 kkal',
    rating: 4.7,
    ulasan: 95,
    img: 'img/es teh.png',
    thumbnails: ['img/es teh.png']
  },
  'teh-hangat': {
    id: 'teh-hangat',
    nama: 'Teh Hangat',
    harga: 4000,
    kategori: 'Minuman',
    deskripsi: 'Teh manis hangat tradisional, cocok dinikmati saat santai bersama keluarga.',
    tags: ['Minuman', 'Hangat', 'Teh'],
    pedas: 0,
    berat: '± 250 ml',
    kalori: '50 kkal',
    rating: 4.6,
    ulasan: 78,
    img: 'img/es teh.png',
    thumbnails: ['img/es teh.png']
  },
  'jeruk-hangat': {
    id: 'jeruk-hangat',
    nama: 'Jeruk Hangat',
    harga: 7000,
    kategori: 'Minuman',
    deskripsi: 'Perasan jeruk asli disajikan hangat, menyegarkan dan menyehatkan tenggorokan.',
    tags: ['Minuman', 'Hangat', 'Jeruk'],
    pedas: 0,
    berat: '± 250 ml',
    kalori: '80 kkal',
    rating: 4.6,
    ulasan: 62,
    img: 'img/es jeruk.png',
    thumbnails: ['img/es jeruk.png']
  },
  'air-mineral': {
    id: 'air-mineral',
    nama: 'Air Mineral',
    harga: 4000,
    kategori: 'Minuman',
    deskripsi: 'Air mineral kemasan untuk menemani santap siang Anda.',
    tags: ['Minuman', 'Air'],
    pedas: 0,
    berat: '600 ml',
    kalori: '0 kkal',
    rating: 4.5,
    ulasan: 45,
    img: 'img/es teh.png',
    thumbnails: ['img/es teh.png']
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = MENU_DATA;
}
